# Configuration for yamllint
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends: relaxed

rules:
  # Line length - accommodate long Kubernetes resource names and URLs
  line-length:
    max: 120
    level: warning

  # Indentation - standard for Kubernetes YAML
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Document boundaries
  document-start:
    present: false  # Don't require --- at start

  # Brackets and braces
  brackets:
    max-spaces-inside: 1
    min-spaces-inside: 0

  braces:
    max-spaces-inside: 1
    min-spaces-inside: 0

ignore: |
  /.secrets.baseline
  /**/templates/**
  /**/*.template.yaml
  /**/*.template.yml
  /**/*.tmpl.yaml
  /**/*.tmpl.yml
