---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
  labels:
    app.kubernetes.io/name: backstage
spec:
  database:
    enableLocalDb: true
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: rhdh-secrets            
    replicas: 1
    route:
      enabled: true
      host: rhdh.apps.cluster-<GUID>.dynamic.redhatworkshops.io
      subdomain: apps.cluster-<GUID>.dynamic.redhatworkshops.io
